// app/(dashboard)/dashboard/resume-upload.tsx
"use client";

import { useState, useRef, useCallback } from "react";
import { Label } from "@/components/ui/label";
import { Resume } from "@/lib/types/resume";

export function ResumeUpload() {
  const [resume, setResume] = useState<Resume | null>(null);
  const [processing, setProcessing] = useState(false);
  const [isDragActive, setIsDragActive] = useState(false);
  const [fileName, setFileName] = useState("");
  const fileInputRef = useRef<HTMLInputElement>(null);
  const acceptedFileTypes = ".pdf, .md, .txt, .doc, .docx";

  const handleUpload = async (file: File) => {
    const formData = new FormData();
    formData.append("file", file);

    console.log("Uploading file:", file);
    setProcessing(true);

    try {
      const response = await fetch("http://127.0.0.1:8000/parse", {
        method: "PUT",
        body: formData,
        headers: {
          Accept: "application/json",
        },
        credentials: "include",
      });

      const result = await response.json();
      console.log(result);

      setProcessing(false);
      setResume(result.data.resume);
    } catch (error) {
      console.error("Error uploading file:", error);
    }
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files && files.length > 0) {
      setFileName(files[0].name);
      handleUpload(files[0]);
    }
  };

  const onDragOver = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragActive(true);
  }, []);

  const onDragLeave = useCallback((event: React.DragEvent<HTMLDivElement>) => {
    event.preventDefault();
    setIsDragActive(false);
  }, []);

  const onDrop = useCallback(
    (event: React.DragEvent<HTMLDivElement>) => {
      event.preventDefault();
      setIsDragActive(false);

      const files = event.dataTransfer.files;
      if (files && files.length > 0) {
        // Check if the file type is valid
        const file = files[0];
        const fileExtension = file.name.split(".").pop()?.toLowerCase();
        const validTypes = acceptedFileTypes
          .split(", ")
          .map((type) => type.replace(".", ""));

        if (fileExtension && validTypes.includes(fileExtension)) {
          if (fileInputRef.current) {
            const dataTransfer = new DataTransfer();
            dataTransfer.items.add(file);
            fileInputRef.current.files = dataTransfer.files;
          }
        } else {
          alert(`Invalid file type. Please upload: ${acceptedFileTypes}`);
        }
      }
    },
    [acceptedFileTypes],
  );

  const openFileDialog = () => {
    if (fileInputRef.current) {
      fileInputRef.current.click();
    }
  };

  return (
    <div className="flex flex-col space-y-4 flex-1">
      <div className="flex flex-col space-y-2 flex-1">
        <Label htmlFor="resume" className="sr-only">
          Resume
        </Label>
        <input
          id="resume"
          type="file"
          className="hidden"
          accept={acceptedFileTypes}
          ref={fileInputRef}
          onChange={handleFileChange}
        />
        <div
          onClick={openFileDialog}
          onDragOver={onDragOver}
          onDragLeave={onDragLeave}
          onDrop={onDrop}
          className={`
            border-2 border-dashed rounded-md p-6 grid place-items-center cursor-pointer transition-colors flex-1
            ${isDragActive ? "border-indigo-500 bg-indigo-500/10 text-indigo-500" : "border-border hover:border-indigo-500 hover:bg-indigo-500/10 hover:text-indigo-500"}
          `}
        >
          <div className="flex flex-col items-center">
            <p className="font-medium text-lg">
              Drag and drop your resume here
            </p>
            <p className="text-xs text-muted-foreground mt-1">
              {acceptedFileTypes}
            </p>
          </div>
        </div>
      </div>
      {resume && (
        <div className="p-8 rounded-md bg-indigo-500/10 text-indigo-200 border border-indigo-500/50 flex-1 overflow-auto">
          {JSON.stringify(resume, null, 2)}
        </div>
      )}
    </div>
  );
}

// src/routes/app/onboarding/ResumeUpload.svelte
<script lang="ts">
	import { PUBLIC_API_URL } from '$env/static/public';
	import { Button } from '@/components/ui/button';
	import { Upload, FileUp, X } from 'lucide-svelte';
	import type { Resume } from '@/types/resume';

	let {
		resumeImport = $bindable(),
		isImporting = $bindable()
	}: { resumeImport: Resume | undefined; isImporting: boolean } = $props();

	let fileInput: HTMLInputElement;
	let isDragging = $state(false);
	let fileName = $state('');

	const acceptedFileTypes = '.pdf, .md, .txt, .doc, .docx';

	function handleDragOver(e: DragEvent) {
		e.preventDefault();
		isDragging = true;
	}

	function handleDragLeave(e: DragEvent) {
		e.preventDefault();
		isDragging = false;
	}

	function handleDrop(e: DragEvent) {
		e.preventDefault();
		isDragging = false;

		const files = e.dataTransfer?.files;
		if (files && files.length > 0) {
			const file = files[0];
			const fileExtension = file.name.split('.').pop()?.toLowerCase();
			const validTypes = acceptedFileTypes.split(', ').map((type) => type.replace('.', ''));

			if (fileExtension && validTypes.includes(fileExtension)) {
				handleFileUpload(file);
			} else {
				alert(`Invalid file type. Please upload: ${acceptedFileTypes}`);
			}
		}
	}

	function handleFileChange(e: Event) {
		const target = e.target as HTMLInputElement;
		const files = target.files;

		if (files && files.length > 0) {
			handleFileUpload(files[0]);
		}
	}

	async function handleFileUpload(file: File) {
		fileName = file.name;
		isImporting = true;

		const formData = new FormData();
		formData.append('file', file);

		try {
			const response = await fetch(`${PUBLIC_API_URL}/parse`, {
				method: 'PUT',
				body: formData,
				headers: {
					Accept: 'application/json'
				},
				credentials: 'include'
			});

			if (!response.ok) {
				throw new Error(`HTTP error! Status: ${response.status}`);
			}

			const result = await response.json();

			if (result.data && result.data.resume) {
				resumeImport = result.data.resume;
			} else if (result.resume) {
				// Alternative response structure
				resumeImport = result.resume;
			}
		} catch (error) {
			console.error('Error uploading resume:', error);
			alert('Failed to upload or parse resume. Please try again.');
		} finally {
			isImporting = false;
		}
	}

	function clearFile() {
		fileName = '';
		if (fileInput) {
			fileInput.value = '';
		}
	}

	function openFileDialog() {
		if (fileInput) {
			fileInput.click();
		}
	}
</script>

<h3 class="text-lg font-semibold">Upload Resume</h3>
<input
	type="file"
	accept={acceptedFileTypes}
	class="hidden"
	bind:this={fileInput}
	onchange={handleFileChange}
/>

{#if fileName}
	<div class="flex gap-2">
		<div
			class="flex w-full items-center justify-between rounded-md border border-border bg-background p-2"
		>
			<div class="flex items-center gap-2">
				<FileUp class="h-5 w-5 text-primary" />
				<span class="text-sm font-medium">{fileName}</span>
			</div>
		</div>
		<Button variant="outline" onclick={clearFile} disabled={isImporting}>
			<X />
		</Button>
	</div>
{:else}
	<button
		class="flex min-h-[200px] flex-col items-center justify-center gap-3 rounded-md border border-dashed
		{isDragging
			? 'border-primary bg-primary/5'
			: 'border-gray-300'} cursor-pointer p-4 transition-colors hover:border-primary hover:bg-primary/5"
		ondragover={handleDragOver}
		ondragleave={handleDragLeave}
		ondrop={handleDrop}
		onclick={openFileDialog}
		type="button"
		disabled={isImporting}
	>
		<Upload class="h-8 w-8 text-primary/80" />
		<div class="text-center">
			<span class="text-muted-foreground">Drag and drop your document here</span>
			<p class="text-xs text-muted-foreground">or click to browse your files</p>
			<p class="mt-1 text-xs text-muted-foreground">File types accepted: pdf, doc, docx, txt, md</p>
		</div>
	</button>
{/if}
